///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("66b73a85-0190-439b-9fb2-6e1480bac622")]
    public partial class DesktopAppRepository : RepoGenBaseFolder
    {
        static DesktopAppRepository instance = new DesktopAppRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DesktopAppRepository element repository.
        /// </summary>
        [RepositoryFolder("66b73a85-0190-439b-9fb2-6e1480bac622")]
        public static DesktopAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopAppRepository() 
            : base("DesktopAppRepository", "/", null, 0, false, "66b73a85-0190-439b-9fb2-6e1480bac622", ".\\RepositoryImages\\DesktopAppRepository66b73a85.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("66b73a85-0190-439b-9fb2-6e1480bac622")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopAppRepositoryFolders
    {
    }
#pragma warning restore 0436
}
