///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterYourName recording.
    /// </summary>
    [TestModule("07cc52aa-d7be-4665-bebe-6fdfcbb23f73", ModuleType.Recording, 1)]
    public partial class EnterYourName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp.DesktopAppRepository repository.
        /// </summary>
        public static global::DesktopApp.DesktopAppRepository repo = global::DesktopApp.DesktopAppRepository.Instance;

        static EnterYourName instance = new EnterYourName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterYourName()
        {
            varUsername = "Krishnag";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterYourName Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("268aed7d-4189-400c-9d6b-0af3dab20c69")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUsername' with focus on 'RxMainFrame.TabPageList.IntroductionContent.TxtUsername'.", repo.RxMainFrame.TabPageList.IntroductionContent.TxtUsernameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TabPageList.IntroductionContent.TxtUsername.PressKeys(varUsername);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.TabPageList.IntroductionContent.SubmitBtn' at Center.", repo.RxMainFrame.TabPageList.IntroductionContent.SubmitBtnInfo, new RecordItemIndex(1));
            repo.RxMainFrame.TabPageList.IntroductionContent.SubmitBtn.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
