///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartApp recording.
    /// </summary>
    [TestModule("18de6536-aa97-43cf-be4b-7dd286185dd2", ModuleType.Recording, 1)]
    public partial class StartApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp.DesktopAppRepository repository.
        /// </summary>
        public static global::DesktopApp.DesktopAppRepository repo = global::DesktopApp.DesktopAppRepository.Instance;

        static StartApp instance = new StartApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartApp()
        {
            varAppPath = "RxDemoApp\\\\RxDemoApp.exe";
            varAppPid = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartApp Instance
        {
            get { return instance; }
        }

#region Variables

        string _varAppPath;

        /// <summary>
        /// Gets or sets the value of variable varAppPath.
        /// </summary>
        [TestVariable("b69a8069-c1c1-4bd6-852c-7b905c431d00")]
        public string varAppPath
        {
            get { return _varAppPath; }
            set { _varAppPath = value; }
        }

        string _varAppPid;

        /// <summary>
        /// Gets or sets the value of variable varAppPid.
        /// </summary>
        [TestVariable("890107d2-d3d6-4b47-a3ac-bbca304902fc")]
        public string varAppPid
        {
            get { return _varAppPid; }
            set { _varAppPid = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $varAppPath in normal mode. Return value bound to $varAppPid.", new RecordItemIndex(0));
            varAppPid = ValueConverter.ToString(Host.Local.RunApplication(varAppPath, "", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'RxMainFrame'", repo.RxMainFrame.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.RxMainFrame.SelfInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
