///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateWelcomeMessage recording.
    /// </summary>
    [TestModule("b8e89bf3-b59a-4003-81d6-e4e9fe0981b5", ModuleType.Recording, 1)]
    public partial class ValidateWelcomeMessage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp.DesktopAppRepository repository.
        /// </summary>
        public static global::DesktopApp.DesktopAppRepository repo = global::DesktopApp.DesktopAppRepository.Instance;

        static ValidateWelcomeMessage instance = new ValidateWelcomeMessage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateWelcomeMessage()
        {
            varUsername = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateWelcomeMessage Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("19eb3692-ccbd-490e-a5e5-4859a990e48c")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$varUsername) on item 'RxMainFrame.TabPageList.IntroductionContent.WelcomeMsg'.", repo.RxMainFrame.TabPageList.IntroductionContent.WelcomeMsgInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.RxMainFrame.TabPageList.IntroductionContent.WelcomeMsgInfo, "Text", varUsername);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
